name: poetry-install

inputs:
  working_directory:
    required: true
    default: "."

runs:
  using: composite
  steps:

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: false
        virtualenvs-path: ${{ github.workspace }}/.poetry
        installer-parallel: true

    - name: Load cached venv
      id: cached-poetry-dependencies
      uses: actions/cache@v3
      with:
        path: ${{ github.workspace }}/.poetry
        key: venv-${{ github.workflow }}-${{ runner.os }}-${{ matrix.python }}-${{ hashFiles('**/poetry.lock') }}

    - name: Install dependencies
      working-directory: ${{ inputs.working_directory }}
      shell: bash
      run: poetry install --no-interaction
