name: bigquery-schema-migrations-dev

on:
  push:
    paths:
      - 'bigquery/migrations/**.sql'
    branches:
      - "develop"
  # TODO: dryrun
  # pull_request:
  #   paths:
  #     - 'bigquery/migrations/**.sql'

permissions:
  id-token: write
  contents: read
  pull-requests: write

concurrency:
  group: migrate-dev

jobs:
  migrate-dev:
    runs-on:
      - dev
      - standard
      - self-hosted
    container:
      image: python:3.10

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Poetry
        id: poetry
        uses: ./.github/actions/poetry/install
      - name: Install gcloud
        id: gcloud
        uses: ./.github/actions/gcp/install
        with:
          workload_identity_provider: projects/518261476924/locations/global/workloadIdentityPools/github-actions/providers/github-actions
          service_account: argo-workflows-deployer@merpay-dataplatform-jp-dev.iam.gserviceaccount.com

      - name: Migrate
        run: |
          poetry run dp bq schema migrate -e dev -p kouzoh-analytics-jp-dev -d merpay_dataplatform_jp -t schema_history_v2 --parent-project merpay-dataplatform-jp-dev
