name: cue-pkg-dump-prod

on:
  push:
    paths:
      - 'pkg/**.cue'
    branches:
      - "main"
  pull_request:
    paths:
      - 'pkg/**.cue'

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  cue:
    runs-on:
      - prod
      - large
      - self-hosted
    container:
      image: python:3.10
    strategy:
      fail-fast: true
      matrix:
        prefix:
          - "./manifests/microservices/^kouzoh-[0-9a-c]+.*$"
          - "./manifests/microservices/^kouzoh-[d-z]+.*$"
          - "./manifests/microservices/^mercari-((?=[0-9a-c]+)(?!admin-gateway)).*$"
          - "./manifests/microservices/mercari-admin-gateway-jp"
          - "./manifests/microservices/^mercari-((?=[d-k]+)(?!item-watch)).*$"
          - "./manifests/microservices/mercari-item-watch-jp"
          - "./manifests/microservices/^mercari-[l-p]+.*$"
          - "./manifests/microservices/^mercari-((?=[q-z]+)(?!user-recommend)).*$"
          - "./manifests/microservices/mercari-user-recommend-jp"
          - "./manifests/microservices/^merpay-((?=[0-9a-b]+)(?!aml-judge)).*$"
          - "./manifests/microservices/mercari-aml-judge-jp"
          - "./manifests/microservices/^merpay-[c-i]+.*$"
          - "./manifests/microservices/^merpay-[j-m]+.*$"
          - "./manifests/microservices/^merpay-[n-z]+.*$"
          - "./manifests/microservices/^souzoh-.*$"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Poetry
        id: poetry
        uses: ./.github/actions/poetry/install
      - name: Install gcloud
        id: gcloud
        uses: ./.github/actions/gcp/install
        with:
          workload_identity_provider: projects/216572124863/locations/global/workloadIdentityPools/github-actions/providers/github-actions
          service_account: argo-workflows-deployer@merpay-dataplatform-jp-prod.iam.gserviceaccount.com
      - name: Install Avro
        id: avro
        uses: ./.github/actions/avro/install
      - name: Install CUE
        id: cue
        uses: ./.github/actions/cue/install

      - name: CUE eval
        id: eval
        run: |
          poetry run dp cue dump --debug --max-worker 20 --prefix "${{ matrix.prefix }}"

      - name: CUE dump
        id: dump
        run: |
          poetry run dp cue dump --max-worker 20 --prefix "${{ matrix.prefix }}" >> $GITHUB_OUTPUT  

      - name: Upload manifests
        id: upload
        uses: ./.github/actions/cue/upload
        with:
          env: prod
          exclude: dev
          bucket: merpay-dataplatform-jp-prod-kubernetes
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dump_outputs: ${{ steps.dump.outputs.cue_files }}
